# Generated by Django 5.2.7 on 2026-01-17 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0006_alter_passage_created_at_alter_question_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reading.question'),
        ),
    ]
