# Generated by Django 5.2.7 on 2026-01-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0007_alter_useranswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user_answer',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
