# Generated by Django 6.0.1 on 2026-01-21 13:41

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0008_alter_useranswer_user_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='attempt',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-updated_date']},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['-updated_date']},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('type_part', models.CharField(choices=[('complete the sentence', 'Complete The Sentence'), ('complete_the_paragraph', 'Complete The Paragraph'), ('reading_comprehension', 'Reading Comprehension')], default='reading_comprehension', max_length=100)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reading.exam')),
                ('tag', models.ManyToManyField(blank=True, to='reading.tag')),
                ('tag_parts', models.ManyToManyField(blank=True, to='reading.tagpart')),
            ],
            options={
                'ordering': ['-updated_date'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reading.part'),
        ),
        migrations.CreateModel(
            name='PartHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('total_answers', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time', models.IntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.part')),
            ],
            options={
                'ordering': ['-updated_date'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='useranswer',
            name='part_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reading.parthistory'),
        ),
        migrations.AddField(
            model_name='exam',
            name='tag_exams',
            field=models.ManyToManyField(blank=True, to='reading.tagexam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='tag_levels',
            field=models.ManyToManyField(blank=True, to='reading.taglevel'),
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
        migrations.RemoveField(
            model_name='question',
            name='passage',
        ),
        migrations.DeleteModel(
            name='Passage',
        ),
    ]
