# Generated by Django 6.0.1 on 2026-01-23 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0010_alter_exam_updated_date_alter_part_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='part_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reading.parthistory'),
        ),
    ]
