# Generated by Django 6.0.1 on 2026-01-24 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0011_alter_useranswer_part_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='tag_parts',
        ),
        migrations.AlterField(
            model_name='part',
            name='type_part',
            field=models.CharField(choices=[('complete_the_sentence', 'Complete The Sentence'), ('complete_the_paragraph', 'Complete The Paragraph'), ('reading_comprehension', 'Reading Comprehension')], default='reading_comprehension', max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='tag_parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reading.tagpart'),
        ),
    ]
